import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = ({
  subsets: ["latin"],
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={inter.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
